version: "3.8"

services:
  # Service name - you can reference this as 'postgres' in your application
  postgres:
    # Official PostgreSQL image from Docker Hub
    # Using version 16 (you can change to 15, 14, etc.)
    image: postgres:16

    # Container name for easy identification
    container_name: my_postgres_db

    # Restart policy - automatically restart if container stops
    restart: unless-stopped

    # Environment variables for PostgreSQL configuration
    # These reference variables from your .env file
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    # Port mapping: host_port:container_port
    # Uses POSTGRES_PORT from .env, defaults to 5432 if not set
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    # Volume mapping for data persistence
    # Without this, data is lost when container is removed
    volumes:
      # Named volume 'postgres_data' stores database files
      - postgres_data:/var/lib/postgresql/data

      # Optional: Mount initialization scripts
      # Any .sql or .sh files here run on first startup
      # - ./init-scripts:/docker-entrypoint-initdb.d

    # Optional: Resource limits
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G

    # Optional: Health check to monitor database status
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define named volumes
# This section is required for the named volume referenced above
volumes:
  postgres_data:
    # Optional: Specify driver options
    # driver: local
